version: '3'

services:
  app:
    build: .
    container_name: fastapi-jwt-auth
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./app.db
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-supersecretkey}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES:-30}
      - REFRESH_TOKEN_EXPIRE_DAYS=${REFRESH_TOKEN_EXPIRE_DAYS:-7}
      - MAIL_USERNAME=${MAIL_USERNAME:-""}
      - MAIL_PASSWORD=${MAIL_PASSWORD:-""}
      - MAIL_FROM=${MAIL_FROM:-noreply@example.com}
      - MAIL_SERVER=${MAIL_SERVER:-smtp.gmail.com}
      - MAIL_PORT=${MAIL_PORT:-587}
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:3000}
    volumes:
      - ./app.db:/app/app.db